server:
  port: 8081
spring:
  profiles: local
  #datasource配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/message?serverTimezone=Asia/Shanghai
    username: root
    password: 123456