server:
  port: 8081
spring:
  profiles: local
  #datasource配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.211.128:3306/message?serverTimezone=Asia/Shanghai
    username: root
    password: root
  #rabbitmq 配置
  rabbitmq:
    host: 192.168.211.128
    port: 5672
    username: root
    password: admin
    virtual-host: message
    publisherReturns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledgeMode: manual
      direct:
        acknowledgeMode: manual
    cache:
      connection:
        mode: connection
        size: 16
      channel:
        size: 64
        checkout-timeout: 0
    template:
      retry:
        enabled: true
        max-attempts: 2